GROQ_API_KEY="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"
AMADEUS_API_KEY="7qexwwS71yimlG7NSiEx0AlUICPJVnPB"
AMADEUS_SECRET_KEY="LZ7Sz0TKm1xeJBEn"
OPENWEATHER_API_KEY="e78bb55ff53d92cb7b6b20652253d816"